version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: claude-hub-db
    environment:
      POSTGRES_USER: claude
      POSTGRES_PASSWORD: dev123456
      POSTGRES_DB: claude_hub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claude"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
